language: cpp

compiler:
    - gcc

# Install dependencies
addons:
  apt:
    packages:
      - graphviz
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - test/testAvltree

after_success:
  - coveralls --root .. -E ".googletest-src." -E ".gtest." -E ".external." -E ".CMakeFiles." -E ".test/..cpp.*"